// اضافة المتغيرات للمشروع
const header                = document.querySelector("header");
const imgPath               = document.getElementById("imgPath");                       //  input image path
const moviePath             = document.getElementById("moviePath");                     //  input movie path 
const movieName             = document.getElementById("movieName");                     //  input movie name
const movieDescription      = document.getElementById("movieDescription");              //  input movie des
const moviekind             = document.getElementById("moviekind");                     //  input movie kind
const filmYear              = document.querySelector("#year-num");                      //  input film year
const actorsName            = document.querySelectorAll(".add-actors-name-w");          //  input all actors name for film
const filmsKind             = document.querySelectorAll(".add-kind-w");                 //  input all kinds for film
const filmTime              = document.querySelector("#add-film-time");                 //  input time film spend
const addActorsName         = document.querySelector("#add-actors-name");               //  input the first input off actor name
const addFilmsKindVar       = document.querySelector("#add-films-kind");                //  input the first input off kind film
const ratingMovie           = document.querySelector(".inp-rating-movie");              //  input rating film
const allLbl                = document.querySelectorAll(".lbl-dark");                   //  all label except label dark key
const classTitle            = document.querySelectorAll(".title");                      //  all title kind film in grid
const txtNameFile           = document.querySelectorAll(".filmName");                   //  all div film name
const datalist              = document.querySelector("#film-name");                     //  datalist for film name to the search box
const movieSearch           = document.querySelector("#movie-search");                  //  search box
const informationFilm       = document.querySelectorAll(".info-film");                  //  button off information of film
const allgrid               = document.querySelectorAll(".grid");
const wTitle1               = document.querySelectorAll(".wTitle");
const whatAbout1            = document.querySelectorAll(".whatAbout");
const watchedBox1           = document.querySelectorAll(".watchedBox");
//const notWatched            = document.querySelector("#not-watched");
const watchedContinar       = document.querySelector(".watched-continar")
const rdoWatched            = document.querySelectorAll(".rdo-watched");
const addGrid               = document.querySelector(".gridAdd");
const btnAdd                = document.querySelector(".btn-add");
const btnClose              = document.querySelector(".btn-close");
const menuBar               = document.querySelector(".main-menu-bar");
const menuBar2              = document.querySelector(".menu-bar-open1");
const menuBar3              = document.querySelector(".menu-bar-open2");
const darkModeOff           = document.querySelector("#dark-mode-off");
const darkModeOn            = document.querySelector("#dark-mode-on");
const darkModeStick         = document.querySelector("#dark-mode-stick");
const darkMode              = document.querySelector(".dark-mode");
const btnSettingMenu        = document.querySelector(".setting-menu");
const imgOpenMenu           = document.querySelector(".img-open-menu");
const imgCloseMenu          = document.querySelector(".img-close-menu");
const imgSearch             = document.querySelector(".img-search");
const imgCloseMenuSearch    = document.querySelector(".img-close-menu-search");
const btnGoTop              = document.querySelector(".btn-top-page");
const isWatched             = document.querySelector("#is-checked");
const txtArea               = document.querySelector("#txt-area");
let   isDarkMode            = false;
let textOfRow               = "";
